name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements.txt found"

      - name: Run tests
        run: |
          pytest || echo "No tests found"
